columns:
  title:
    type: text
    options:
      editable : true
      label: admin.event.title

  date:
    type: datetime
    options:
      label: admin.event.datetime

  eventMaster:
    type: entity
    options:
      relation_field: eventMaster
      field_mapping: ['username', 'email']
      value_format: "%s (%s)"
      label: admin.event.event_master

  actions:
    type: action
    options:
      label: admin.event.actions
      field_mapping: [ id ]
      actions:
        edit:
          route_name: "fsi_admin_crud_edit"
          additional_parameters: { element: event }
          parameters_field_mapping: { id: id }

