fos_user:
    db_driver: orm
    firewall_name: main
    user_class: KrakDevs\WebBundle\Entity\User
    from_email:
        address:        krakdevs@gmail.com
        sender_name:    KrakDevs
    registration:
        confirmation:
            enabled: true

fsi_doctrine_extensions:
    orm:
        default:
            uploadable: true

fsi_gallery:
    db_driver: orm
    gallery_class: KrakDevs\WebBundle\Entity\Gallery
    photo_class: KrakDevs\WebBundle\Entity\Photo

stof_doctrine_extensions:
    default_locale: en
    orm:
        default:
            sluggable: true

hwi_oauth:
    firewall_name: secured_area
    fosub:
        properties:
          github: githubId
    connect:
        account_connector: krakdevs_web.user.provider
    resource_owners:
        github:
            type:          github
            client_id:     %github_client_id%
            client_secret: %github_client_secret%
            scope: ~
    http_client:
        timeout: 30